services:
  postgres:
    image: postgres:15-alpine
    container_name: wallet-postgres
    environment:
      POSTGRES_DB: walletdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d walletdb"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    restart: on-failure:3
    command: >
      postgres 
      -c max_connections=100 
      -c shared_buffers=128MB

  wallet-service:
    build: .
    container_name: wallet-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # ТОЧНО такие имена переменных:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/walletdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8080
      # УБЕРАЮ профиль docker пока что:
      # SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8081:8080"
    restart: unless-stopped

volumes:
  postgres_data: